# Generated by Django 4.0 on 2023-07-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_new_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='new_field',
            field=models.PositiveIntegerField(default=11),
        ),
    ]
