# Generated by Django 4.0 on 2023-07-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='new_field',
        ),
    ]
