services:
  nginx:
    image: gabrielesavoia/uni-nginx:latest

  app:
    image: gabrielesavoia/uni-app:latest
    environment:
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_HOST
      - MARIADB_PORT
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - ${MARIADB_PORT}:${MARIADB_PORT}

volumes:
  mariadb_data: